COUNTRY_OPTIONS = (
("USA", "United States"),
("AFG","Afghanistan"),
("ALB","Albania"),
("ALG","Algeria"),
("AND","Andorra"),
("ANG","Angola"),
("ANT","Antigua and Barbuda"),
("ARG","Argentina"),
("ARM","Armenia"),
("AUS","Australia"),
("AUT","Austria"),
("AZE","Azerbaijan"),
("BAH","Bahamas"),
("BAI","Bahrain"),
("BAN","Bangladesh"),
("BAR","Barbados"),
("BES","Belarus"),
("BEL","Belgium"),
("BEM","Belize"),
("BEN","Benin"),
("BHU","Bhutan"),
("BOL","Bolivia"),
("BOS","Bosnia and Herzegovina"),
("BOT","Botswana"),
("BRA","Brazil"),
("BRU","Brunei"),
("BUL","Bulgaria"),
("BUK","Burkina Faso"),
("BUR","Burma"),
("BUU","Burundi"),
("CAN","Canada"),
("CAB","Cambodia"),
("CAM","Cameroon"),
("CAP","Cape Verde"),
("CAE","Central African Republic"),
("CHA","Chad"),
("CHL","Chile"),
("CHN","China"),
("COL","Colombia"),
("COM","Comoros"),
("RCB","Congo Brazzaville"),
("CON","Congo Kinshasa"),
("COS","Costa Rica"),
("IVO","Cote D&#39; Ivoire"),
("CRO","Croatia"),
("CYP","Cyprus"),
("CZE","Czech Republic"),
("DEN","Denmark"),
("DJI","Djibouti"),
("DON","Dominica"),
("DOM","Dominican Republic"),
("ETM","East Timor"),
("ECU","Ecuador"),
("EGY","Egypt"),
("ELS","El Salvador"),
("EQU","Equatorial Guinea"),
("ERI","Eritrea"),
("EST","Estonia"),
("ETH","Ethiopia"),
("FIJ","Fiji"),
("FIN","Finland"),
("FRA","France"),
("GAB","Gabon"),
("GEO","Georgia"),
("GER","Germany"),
("GHA","Ghana"),
("GRE","Greece"),
("GRN","Grenada"),
("GUA","Guatemala"),
("GUI","Guinea"),
("GUU","Guinea-Bissau"),
("GUY","Guyana"),
("HAI","Haiti"),
("VAT","Holy See"),
("HND","Honduras"),
("HUN","Hungary"),
("ICE","Iceland"),
("IND","India"),
("INS","Indonesia"),
("IRC","Iraq"),
("IRE","Ireland"),
("ISR","Israel"),
("ITA","Italy"),
("JAM","Jamaica"),
("JPN","Japan"),
("JOR","Jordan"),
("KAZ","Kazakhstan"),
("KEN","Kenya"),
("KIR","Kiribati"),
("KUW","Kuwait"),
("KYR","Kyrgyzstan"),
("LAS","Laos"),
("LAT","Latvia"),
("LEB","Lebanon"),
("LES","Lesotho"),
("LIB","Liberia"),
("LIY","Libya"),
("LIE","Liechtenstein"),
("LIT","Lithuania"),
("LUX","Luxembourg"),
("MAE","Macedonia"),
("MDG","Madagascar"),
("MAI","Malawi"),
("MAL","Malaysia"),
("MAM","Maldives"),
("MAN","Mali"),
("MAT","Malta"),
("MHL","Marshall Islands"),
("MAU","Mauritania"),
("MAV","Mauritius"),
("MEX","Mexico"),
("FSM","Micronesia"),
("MOL","Moldova"),
("MOC","Monaco"),
("MNE","Montenegro"),
("MON","Mongolia"),
("MOR","Morocco"),
("MOZ","Mozambique"),
("NAM","Namibia"),
("NAU","Nauru"),
("NEP","Nepal"),
("NEA","Netherlands Antilles"),
("NET","Netherlands"),
("NEW","New Zealand"),
("NIC","Nicaragua"),
("NIE","Niger"),
("NIG","Nigeria"),
("NKO","North Korea"),
("NOR","Norway"),
("OMA","Oman"),
("PAK","Pakistan"),
("PLW","Palau"),
("PAN","Panama"),
("PAP","Papua New Guinea"),
("PAR","Paraguay"),
("PER","Peru"),
("PHI","Philippines"),
("POL","Poland"),
("POR","Portugal"),
("QAT","Qatar"),
("ROM","Romania"),
("RUS","Russia"),
("RWA","Rwanda"),
("SKA","Saint Kitts and Nevis"),
("SLU","Saint Lucia"),
("STV","Saint Vincent and the Grenadines"),
("WSM","Samoa"),
("SMA","San Marino"),
("SAO","Sao Tome Principe"),
("SAU","Saudi Arabia"),
("SEN","Senegal"),
("SER","Serbia"),
("SEY","Seychelles"),
("SIE","Sierra Leone"),
("SIN","Singapore"),
("SLA","Slovakia"),
("SLO","Slovenia"),
("SOL","Solomon Islands"),
("SOM","Somalia"),
("SOR","South Africa"),
("SKO","South Korea"),
("SPA","Spain"),
("SRI","Sri Lanka"),
("SUR","Suriname"),
("SWA","Swaziland"),
("SWE","Sweden"),
("SWI","Switzerland"),
("SYR","Syria"),
("TAJ","Tajikistan"),
("TAN","Tanzania"),
("THA","Thailand"),
("TOG","Togo"),
("TON","Tonga"),
("TRI","Trinidad and Tobago"),
("TUN","Tunisia"),
("TUR","Turkey"),
("TUM","Turkmenistan"),
("TUV","Tuvalo"),
("UGA","Uganda"),
("UKR","Ukraine"),
("UAE","United Arab Emirates"),
("GBR","United Kingdom"),
("URN","Uruguay"),
("UZB","Uzbekistan"),
("VAN","Vanuatu"),
("VEN","Venezuela"),
("VIE","Vietnam"),
("YEM","Yemen"),
("ZAM","Zambia"),
("ZIM","Zimbabwe"),)
